<a href="https://colab.research.google.com/github/ANAGHA-SREYAS/entri_dsml_tasks/blob/main/anagha_vp_task5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.NUMPY

1. How to extract all odd numbers from arr?

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a=[]
for x in arr:
  if x%2!=0:
    a.append(x)

print(np.array(a))


[1 3 5 7 9]


2. Replace all odd numbers in arr with -1 without changing

In [ ]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr=np.copy(arr)
new_arr[new_arr%2!=0]=-1
new_arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

 3.Convert a 1D array to a 2D array with 2 rows

In [ ]:
import numpy as np
arr=np.arange(10)

#Desired Output:
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])
x=arr.reshape(2,-1)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

4. Stack arrays a and b vertically

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])
x=np.vstack((a,b))
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

5. Stack the arrays a and b horizontally.

In [ ]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#Desired Output:

#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
x=np.hstack((a,b))
x

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

6.How to get the common items between two python numpy arrays?
Get the common items between a and b

In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
new_arr=np.intersect1d(a,b)
new_arr

array([2, 4])

7.How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
x=np.isin(a,b,invert=True)
new_arr=a[x]
new_arr



array([1, 2, 3, 4])

8. How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match

In [ ]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#Desired Output:

#> (array([1, 3, 5, 7]),)
x=np.where(a==b)
print(x)

(array([1, 3, 5, 7]),)


9. How to extract all numbers between a given range from a numpy array?
Get all items between 5 and 10 from a

In [ ]:
import numpy as np

a = np.array([2, 6, 1, 9, 10, 3, 27])
#Desired Output:

#(array([6, 9, 10]),)
x=np.where((a>5)&(a<=10))
new_arr=a[x]
new_arr






array([ 6,  9, 10])

# PANDAS

1. Write a Pandas program to convert a dictionary to a Pandas series.

Sample Series:

Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

In [ ]:

import pandas as pd
dict1={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
series=pd.Series(dict1)
series

a    100
b    200
c    300
d    400
e    800
dtype: int64

2. Write a Pandas program to convert a NumPy array to a Pandas series.

Sample Series:

  NumPy array:
[10 20 30 40 50]

In [ ]:
import pandas as pd
import numpy as np
arr=np.array([10,20,30,40,50])
series=pd.Series(arr)
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

3. Write a Pandas program to change the data type of given a column or a Series.

Sample Series:

    Original Data Series:

0       100

1       200

2    python

3    300.12

4       400

dtype: object

Change the said data type to numeric:

0    100.00

1    200.00

2       NaN

3    300.12

4    400.00

dtype: float64

In [ ]:
import pandas as pd
lst=[100,200,'python',300.12,400]
a=pd.Series(lst)

new_type=pd.to_numeric(a,errors="coerce")
print(a)
print(new_type)

0       100
1       200
2    python
3    300.12
4       400
dtype: object
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64


4. Write a Pandas program to convert the first column of a DataFrame as a Series.

In [ ]:
import pandas as pd
dict1={'col1':[1,2,3,4,7,11],'col2':[4,5,6,9,5,0],'col3':[7,5,8,12,1,11]}
df=pd.DataFrame(dict1)
print(df)

print(df['col1'])

   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64


5. Write a Pandas program to convert a given Series to an array.

In [ ]:
import pandas as pd
import numpy as np
lst=[100,200,'python',300.12,400]
series=pd.Series(lst)
print(series)
arr=np.array(series)
arr

0       100
1       200
2    python
3    300.12
4       400
dtype: object


array([100, 200, 'python', 300.12, 400], dtype=object)

6 Write a Pandas program to convert Series of lists to one Series.

In [ ]:
import pandas as pd
lst=[['red','green','white'],['red','black'],['yellow']]
srs1=pd.Series(lst)
print(srs1)
new_srs=srs1.explode()
new_srs


0    [red, green, white]
1           [red, black]
2               [yellow]
dtype: object


0       red
0     green
0     white
1       red
1     black
2    yellow
dtype: object

7.Write a Pandas program to sort a given Series.

In [ ]:
import pandas as pd
lst=[100,200,'python',300.12,400]
srs1=pd.Series(lst)
srs2=pd.to_numeric(srs1,errors='coerce')
sorted_series=srs2.dropna().sort_values()
sorted_series


0    100.00
1    200.00
3    300.12
4    400.00
dtype: float64

# Pandas DataFrame


1.Write a Pandas program to create a dataframe from a dictionary and display it

In [ ]:
import pandas as pd
dict1={'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
df=pd.DataFrame(dict1)
df

X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

3. Write a Pandas program to get the first 3 rows of a given DataFrame.

In [ ]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
print(df.head(n=3))

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


4.Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [ ]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
print(df[['name','score']])

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


5. Write a Pandas program to select the specified columns and rows from a given data frame.

In [ ]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
print(df.loc[['b','d','f','g'],['score','qualify']])

   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes


6. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2

In [ ]:
import pandas as pd
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
selected_rows = df[df['attempts'] > 2]
selected_rows

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

7. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df=pd.DataFrame(exam_data,index=labels)
selected_rows=df[df['score'].isnull()]
selected_rows

name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

8. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
selected_rows=df[(df['score']>15) &  (df['score']<20)]

selected_rows

name  score  attempts qualify
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes

9. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
selected_rows=df[(df['score']>15)&(df['attempts']<2)]
selected_rows

name  score  attempts qualify
j  Jonas   19.0         1     yes

10. Write a Pandas program to change the score in row 'd' to 11.5.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
df.loc['d','score']=11.5
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

11. Write a Pandas program to calculate the sum of the examination attempts by the students.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
sum_of_attempts=df['attempts'].sum()
sum_of_attempts

19

12. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
mean=df['score'].mean()
mean

13.5625

13. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
df['qualify']=df['qualify'].replace({'yes':True,'no':False})
df


name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

14. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
df['name']=df['name'].replace('James','Suresh')
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

15. Write a Pandas program to delete the 'attempts' column from the DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
df.drop(['attempts'],axis=1,inplace=True)
df

name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

16. Write a Pandas program to insert a new column in existing DataFrame

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
color=['red','blue','green','yellow','orange','red','black','yellow','blue','violet']
df['color']=color
df

name  score  attempts qualify   color
a  Anastasia   12.5         1     yes     red
b       Dima    9.0         3      no    blue
c  Katherine   16.5         2     yes   green
d      James    NaN         3      no  yellow
e      Emily    9.0         2      no  orange
f    Michael   20.0         3     yes     red
g    Matthew   14.5         1     yes   black
h      Laura    NaN         1      no  yellow
i      Kevin    8.0         2      no    blue
j      Jonas   19.0         1     yes  violet

17. Write a Pandas program to rename columns of a given DataFrame

In [ ]:
import pandas as pd
dict1={'col1':[1,2,3],'col2':[4,5,6],'col3':[7,8,9]}
df=pd.DataFrame(dict1)
df=df.rename(columns={'col1':'column1','col2':'column2','col3':'column3'})

df

column1  column2  column3
0        1        4        7
1        2        5        8
2        3        6        9

18. Write a Pandas program to select rows from a given DataFrame based on values in some columns.

In [ ]:
import pandas as pd
dict1={'col1':[1,4,3,4,5],'col2':[4,5,6,7,8],'col3':[7,8,9,0,1]}
df=pd.DataFrame(dict1)
#rows for col1 value==4
selected_rows=df[df['col1']==4]
selected_rows

col1  col2  col3
1     4     5     8
3     4     7     0

19. Write a Pandas program to add one row in an existing DataFrame.

In [ ]:
import pandas as pd
dict1={'col1':[1,4,3,4,5],'col2':[4,5,6,7,8],'col3':[7,8,9,0,1]}
df=pd.DataFrame(dict1)
new_data={'col1':10,'col2':11,'col3':12}
new_df=df.append(new_data,ignore_index=True)
new_df

<ipython-input-114-e0fe635ed744>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  new_df=df.append(new_data,ignore_index=True)


col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12

20. Write a Pandas program to replace all the NaN values with Zero's in a column of a dataframe

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(exam_data,index=labels)
df['score'].fillna(0,inplace=True)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    0.0         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    0.0         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

21. Write a Pandas program to count the NaN values in one or more columns in DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df=pd.DataFrame(exam_data)
count=df.isna().sum().sum()
count

2

22. Write a Pandas program to drop a list of rows from a specified DataFrame.

In [ ]:
import pandas as pd
dict1={'col1':[1,4,3,4,5],'col2':[4,5,6,7,8],'col3':[7,8,9,0,1]}
df=pd.DataFrame(dict1)
remove=[1,3]
new_df=df.drop(index=remove)
new_df

col1  col2  col3
0     1     4     7
2     3     6     9
4     5     8     1

23. . Write a Pandas program to convert DataFrame column type from string to datetime.

In [ ]:
import pandas as pd
data = {'String Date': ['3/11/2000', '3/12/2000', '3/13/2000']}
df = pd.DataFrame(data)
print(df)

df['String Date'] = pd.to_datetime(df['String Date'], format='%m/%d/%Y')
print("\nDataFrame after conversion:")
print(df)

  String Date
0   3/11/2000
1   3/12/2000
2   3/13/2000

DataFrame after conversion:
  String Date
0  2000-03-11
1  2000-03-12
2  2000-03-13


24. Write a Pandas program to find the row for where the value of a given column is maximum.

In [ ]:
import pandas as pd
dict1={'col1':[1,2,3,4,7],'col2':[4,5,6,9,5],'col':[7,8,12,1,11]}
df=pd.DataFrame(dict1)
for col in df.columns:
   max_row = df[col].idxmax()
   print(f"Row where {col} has maximum value:")
   print(max_row)



Row where col1 has maximum value:
4
Row where col2 has maximum value:
3
Row where col has maximum value:
2


25. Write a Pandas program to get the datatypes of columns of a DataFrame.

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
df=pd.DataFrame(exam_data)
for col in df.columns:
  datatype=df[col].dtypes
  print(f"Data types of the '{col}' of the said DataFrame:")
  print(datatype)
  print()

Data types of the 'name' of the said DataFrame:
object

Data types of the 'score' of the said DataFrame:
float64

Data types of the 'attempts' of the said DataFrame:
int64

Data types of the 'qualify' of the said DataFrame:
object



26. Write a Pandas program to group by the first column and get second column as lists in rows.

In [ ]:
import pandas as pd
dict1={'col1':['c1','c1','c2','c2','c2','c3','c2'],'col2':[1,2,3,3,4,6,5]}
df=pd.DataFrame(dict1)
x=df.groupby('col1')['col2'].agg(list)

x

col1
c1          [1, 2]
c2    [3, 3, 4, 5]
c3             [6]
Name: col2, dtype: object


27 Write a Pandas program to count number of columns of a DataFrame.

In [ ]:
import pandas as pd
dict1={'col1':[1,2,3,4,7],'col2':[4,5,6,9,5],'col':[7,8,12,1,11]}
df=pd.DataFrame(dict1)
print(f'number of columns:{len(df.columns)}')

number of columns:3


28. Write a Pandas program to get first n records of a DataFrame.

In [ ]:
import pandas as pd
dict1={'col1':[1,2,3,4,7],'col2':[4,5,6,9,5],'col':[7,8,12,1,11]}
df=pd.DataFrame(dict1)
def n_records(n):
  first_n_records=df.head(n)
  print(first_n_records)
print(n_records(3))

   col1  col2  col
0     1     4    7
1     2     5    8
2     3     6   12
None


29. Write a Pandas program to get last n records of a DataFrame.

In [ ]:
import pandas as pd
dict1={'col1':[1,2,3,4,7,11],'col2':[4,5,6,9,5,0],'col':[7,5,8,12,1,11]}
df=pd.DataFrame(dict1)
def n_records(n):
  last_n_records=df.tail(n)
  print(last_n_records)
print(n_records(3))

   col1  col2  col
3     4     9   12
4     7     5    1
5    11     0   11
None



30. Write a Pandas program to get topmost n records within each group of a DataFrame

In [ ]:
import pandas as pd
d = {'col1': [1, 2, 3, 4, 7, 11], 'col2': [4, 5, 6, 9, 5, 0], 'col3': [7, 5, 8, 12, 1,11]}
df = pd.DataFrame(data=d)
print("Original DataFrame")
print(df)
print("\ntopmost n records within each group of a DataFrame:")
df1 = df.nlargest(3, 'col1')
print(df1)
df2 = df.nlargest(3, 'col2')
print(df2)
df3 = df.nlargest(3, 'col3')
print(df3)


31. Write a Pandas program to add a prefix or suffix to all columns of a given DataFrame.

In [ ]:
import pandas as pd
dict1={'w':[68,75,86,80,66],'x':[78,85,96,80,86],'y':[84,94,89,83,86],'z':[86,97,96,72,83]}
df=pd.DataFrame(dict1)
print('original dataframe:\n',df)
a=df.add_prefix('A_')
b=df.add_suffix('_1')
print()
print(a)
print()
print(b)

original dataframe:
     w   x   y   z
0  68  78  84  86
1  75  85  94  97
2  86  96  89  96
3  80  80  83  72
4  66  86  86  83

   A_w  A_x  A_y  A_z
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83

   w_1  x_1  y_1  z_1
0   68   78   84   86
1   75   85   94   97
2   86   96   89   96
3   80   80   83   72
4   66   86   86   83


32. Write a Pandas program to convert continuous values of a column in a given DataFrame to categorical.

In [ ]:
import pandas as pd
data={ 'Name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Syed Wharton'],'Age': [18, 22, 40, 50, 80] }
df=pd.DataFrame(data)
df['age_grp']=pd.cut(df['Age'],bins=[0,18,65,99],labels=['kids','adults','elderly'])
print(f'age group:\n{df["age_grp"]}')

age group:
0       kids
1     adults
2     adults
3     adults
4    elderly
Name: age_grp, dtype: category
Categories (3, object): ['kids' < 'adults' < 'elderly']


33. Write a Pandas program to append rows to an existing DataFrame and display the combined data.

In [ ]:
import pandas as pd
data={'student_id':['s1','s2','s3','s4','s5'],'name':['Danniella Fenton','Ryder Storey','Bryce Jensen','Ed Bernal',' Kwame Morin'],'marks':[200,210,190,22,199]}
df=pd.DataFrame(data)
new_row={'student_id':'s6','name':'Scarlette Fisher','marks':205}
df=df.append(new_row,ignore_index=True)
df

34 Write a Pandas program to join the two given dataframes along rows and merge with another dataframe along the common column id.

In [ ]:
import pandas as pd
student_data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Danniella Fenton', 'Ryder Storey', 'Bryce Jensen', 'Ed Bernal', 'Kwame Morin'],
        'marks': [200, 210, 190, 222, 199]})

student_data2 = pd.DataFrame({
        'student_id': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Scarlette Fisher', 'Carla Williamson', 'Dante Morse', 'Kaiser William', 'Madeeha Preston'],
        'marks': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'exam_id': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

print("Original DataFrames:")
print(student_data1)
print(student_data2)
print(exam_data)

print("\nJoin first two said dataframes along rows:")
result_data = pd.concat([student_data1, student_data2])
print(result_data)

print("\nNow join the said result_data and df_exam_data along student_id:")
final_merged_data = pd.merge(result_data, exam_data, on='student_id')
print(final_merged_data)


Original DataFrames:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bernal    222
4         S5       Kwame Morin    199
  student_id              name  marks
0         S4  Scarlette Fisher    201
1         S5  Carla Williamson    200
2         S6       Dante Morse    198
3         S7    Kaiser William    219
4         S8   Madeeha Preston    201
   student_id  exam_id
0          S1       23
1          S2       45
2          S3       12
3          S4       67
4          S5       21
5          S7       55
6          S8       33
7          S9       14
8         S10       56
9         S11       83
10        S12       88
11        S13       12

Join first two said dataframes along rows:
  student_id              name  marks
0         S1  Danniella Fenton    200
1         S2      Ryder Storey    210
2         S3      Bryce Jensen    190
3         S4         Ed Bern